logging:
    level: INFO
http:
  port: 8443
  adminPort: 58443
  connectorType: nonblocking+ssl
  ssl:
      keyStore: ${ssl.cert.dir}/ssl.pfx
      keyStorePassword: zapp_pass
      keyStoreType:     pkcs12

metricService:
    jobSize: 1024
    highCollisionMark: 200000
    lowCollisionMark: 100000
    minTimeBetweenBroadcast: 500
    tsdbWriterThreads: 2
    openTsdbClientPool:
      maxKeepAliveTime: 300000
      minTestTime:       60000

      clients:
        - {host: localhost, port: 4242}

      clientFactory:
        keepAlive:          true
        sendBufferSize:     16384
        receiveBufferSize:  16384
        connectTimeout:     500
        soTimeout:          10
