logging:
    level: INFO
http:
  port: 8443
  adminPort: 58443
  connectorType: nonblocking+ssl
  ssl:
      keyStore: ${ssl.cert.dir}/ssl.pfx
      keyStorePassword: zapp_pass
      keyStoreType:     pkcs12

metricService:
    jobSize: 1000
    highCollisionMark: 200000
    lowCollisionMark: 100000
    minTimeBetweenBroadcast: 500
    tsdbWriterThreads: 1
    maxIdleTime: 1000
    openTsdbClientPool:
      maxKeepAliveTime: 300000
      minTestTime:       60000
      clientBufferSize:  65536
      clients:
        - {host: localhost, port: 4242}

      clientFactory:
        keepAlive:          true
        connectTimeout:     1000
        soTimeout:          50
