logging:
    level: INFO
http:
  port: 8443
  connectorType: nonblocking+ssl
  ssl:
      keyStore: ${ssl.cert.dir}/ssl.pfx
      keyStorePassword: zapp_pass
      keyStoreType:     pkcs12

metric_service:
  inputBufferSize: 1024
  opentsdb_client:
      hostName: localhost
      port:     4242
